### ISSUE TITLE
dt relocate to be applied on all `values_smth.yaml` files

### ISSUE THREAD

**Issue by BLaurent** [vmware-labs/distribution-tooling-for-helm#52]
### Is your feature request related to a problem? Please describe.

When performing a `charts relocate CHART_PATH OCI_URI` only `values.yaml` is updated. This can be very handy to apply the relocation to all `values_smth.yaml` present in the chart. Charts can include various `values_smth.yaml` files that are used depending of the context.

### Describe the solution you'd like

The cli could provide an extra flag like `helm`
```sh
 -f, --values strings                             specify values in a YAML file or a URL (can specify multiple) 
```
If no flag applied keep the current behaviour be applying update only to `values.yaml`.
If flag applied update only files pass as argument.

### Additional context

Changes in `pkg/relocator/chart.go` is needed to take in account additional files fortunately helm chart loader already load all canonical (Chart.yaml, values.yaml, values.schema.json, templates/, charts/ ) and other non canonical files already.

**Comment by BLaurent** [comment]
Hi @alemorcuq,

Thanks for your reply, I do not know how you do the triage for such a feature. Do you run some sort of planning with a fixed release date, like you do 3/4 release big per year, with some fixes and patches in between or just go with the flow and tag when you feel the need ?

Thanks in advance.

**Comment by mpermar** [comment]
@BLaurent , we are doing some [chart syncer](https://github.com/bitnami/charts-syncer) revamp to use `dt` and this issue request should come exactly after that. It's a very good idea. Can't put dates but should be really in the next few couple of weeks.

**Comment by alemorcuq** [comment]
@BLaurent, we have released [version 0.4.0](https://github.com/vmware-labs/distribution-tooling-for-helm/releases/tag/v0.4.0) including a new `--version` flag in the `charts relocate` and `unwrap` commands. Thanks for taking the time to request this feature and let us know any feedback you may have.

**Comment by BLaurent** [comment]
Nice !!!, Thanks for implementing this.
I've looked at the MR, there is a lot of files with very minor modifications, I guess you've fixed lint warning as well

**Comment by alemorcuq** [comment]
> Nice !!!, Thanks for implementing this. I've looked at the MR, there is a lot of files with very minor modifications, I guess you've fixed lint warning as well

Yes, the linter went crazy on me.

If you are curious about the implementation, you can see it in https://github.com/vmware-labs/distribution-tooling-for-helm/pull/56/commits/508ba33381cb51289b41f31dc55a7626b2e5335a
