### ISSUE TITLE
Invalid path when searching Images.lock

### ISSUE THREAD

**Issue by BLaurent** [vmware-labs/distribution-tooling-for-helm#70]
### Describe the bug

I am creating wrap.tgz package and just want to get some info about it:

```
helm dt info simple-web-api-0.7.5.wrap.tgz
failed to load Images.lock: Images.lock not found in wrap
Error: plugin "dt" exited with error
```

Plugin info:
```
helm dt version
Distribution Tooling for Helm v0.4.1
Built on: 2024-04-04T15:45:20Z
```

OS info:
```
OS: macOS 14.4 23E214 arm64
```

### Reproduction steps

1. Create a wrap file `helm dt wrap ./path_to_helm_chart`
2. Execute `helm dt info ./path_to_wrap.tgz`

### Expected behavior

When I do `tar tvfz simple-web-api-0.7.5.wrap.tgz` 
I have this output : 
```
  simple-web-api-0.7.5/chart
  simple-web-api-0.7.5/chart/.helmignore
  simple-web-api-0.7.5/chart/.imgpkg
  simple-web-api-0.7.5/chart/.imgpkg/bundle.yml
  simple-web-api-0.7.5/chart/.imgpkg/images.yml
  simple-web-api-0.7.5/chart/Chart.lock
  simple-web-api-0.7.5/chart/Chart.yaml
  simple-web-api-0.7.5/chart/Chart_template.yaml
  simple-web-api-0.7.5/chart/Images.lock
  simple-web-api-0.7.5/chart/README.md
  simple-web-api-0.7.5/chart/charts
```
`Images.lock` is in a sub-directory named `chart` due [to](https://github.com/vmware-labs/distribution-tooling-for-helm/blob/7798d72aebd2ed7b1655ccb4f41b68d2d4f0a750/pkg/wrapping/wrap.go#L108)

But in [this](https://github.com/vmware-labs/distribution-tooling-for-helm/blob/7798d72aebd2ed7b1655ccb4f41b68d2d4f0a750/pkg/chartutils/chartutils.go#L168)
`StripComponents` is set to `1`. 
The `Images.lock` cannot be found as the method [here](https://github.com/vmware-labs/distribution-tooling-for-helm/blob/7798d72aebd2ed7b1655ccb4f41b68d2d4f0a750/pkg/utils/tar.go#L117) will return `chart/Images.lock` and the test is done with `Images.lock`

**Comment by alemorcuq** [comment]
Thanks for reporting. We will work on a fix.

**Comment by BLaurent** [comment]
If I may, there is smth, I do not understand.
The `dt info` command is documented to work on wrapped chart as shown in the readme.
However it does work when passing a chart directory. Handy it is for sure but all the tests are built around assumption the chart directory is rendered at the root of the temp directory.

**Comment by BLaurent** [comment]
I've proposed this PR #75
