### ISSUE TITLE
Support `helm.sh/images` as annotation to list Helm chart images

### ISSUE THREAD

**Issue by FraPazGal** [vmware-labs/distribution-tooling-for-helm#74]
### Is your feature request related to a problem? Please describe.

Trying to create an images lock will not produce the expected result if the annotation used to list the Helm chart images is different from `images`. This goes against [HIP-0015](https://github.com/helm/community/blob/main/hips/hip-0015.md), which establishes the annotation `helm.sh/images` as a future standard.

### Describe the solution you'd like

For `dt` to support the usage of any of the two `images` or `helm.sh/images` annotations.

### Describe alternatives you've considered

Using the currently supported `images` annotation works as expected but it would be preferable to be able to use `helm.sh/images` as defined by HIPs.

**Comment by mpermar** [comment]
Hey @FraPazGal . Have you tried with the `--annotations-key` flag?

**Comment by FraPazGal** [comment]
That works perfectly, thanks for the help @mpermar!
