### ISSUE TITLE
feat: allow additional, optional, images push with latest tag

### ISSUE THREAD

**Issue by migmartri** [vmware-labs/distribution-tooling-for-helm#81]
### Is your feature request related to a problem? Please describe.

We use the dt plugin to distribute our Charts and Container images, which works great (modulo this other issue #80 :).

The problem comes when the user wants to enable some scans on the latest images relocated directly. Not through the chart but directly. This means that they'd like access to the `latest` tag. 

### Describe the solution you'd like

When the tool pushes the images to the destination, it would be great to optionally also push them with latest tag. Note that this should not affect the chart rewrite process, that one will keep using tags, but just the push mechanism.

### Describe alternatives you've considered

For this use-case we are pulling/pushing images ourselves in another parallel process than the relocation of the chart. We'd like to consolidate it by using this tool alone.

Thanks

**Comment by mpermar** [comment]
I'm not sure I understand. Are you suggesting that it would be nice to add new tags to the relocated images (e.g. latest)?

**Comment by juan131** [comment]
Hi @migmartri 

> The problem comes when the user wants to enable some scans on the latest images relocated directly. Not through the chart but directly. This means that they'd like access to the latest tag.

IMO we're mixing up concepts, we cannot assume the `latest` tag points to the latest relocated image. `latest` is usually used for maintainers to point developers to the image to use but it doesn't mean it's the latest image published.

For instance, imagine you have two charts that include the PostgreSQL image so you have you in your target registry PostgreSQL container images from both charts. If one of your charts is based on PostgreSQL `15.x` and the other is based on `16.x`, would you like relocations affecting the chart that uses `15.x` to update `latest`? It'd be weird to have `latest` pointing to a `15.x` image when you have `16.x` images in the same registry.

**Comment by migmartri** [comment]
Hi @juan131, I think you are right. My proposal can be quite dangerous in the context of multiple charts and their dependencies. 

I'll close it and will keep pushing manually `latest` ourselves.

Thanks for the response!
